[tool.poetry]
name = "python-3-from-sergey-b"
version = "0.1.0"
description = ""
authors = ["Alexandr_Tikhonov <tihas75@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
